### ISSUE TITLE
The list of manufactures is really long

### ISSUE THREAD

**Issue by GermanBluefox** [PArns/ioBroker.amazon-dash#10]
It will be more efficient if just a MACs in one array will be listed

**Comment by GermanBluefox** [comment]
You can cut it to just:
var MACs = [
"747548",
"F0D2F1",
"8871E5",
"74C246",
"F0272D",
"34D270",
"0C47C9",
"A002DC",
"AC63BE",
"44650D",
"50F5DA",
"84D6D0"
];

**Comment by PArns** [comment]
Yes you're right! I didn't want to maintain that list manually
Try the latest version ...
