### ISSUE TITLE
0.2.1 not working

### ISSUE THREAD

**Issue by Vrumfondel** [PArns/ioBroker.amazon-dash#13]
Release 0.2.1 is not working any more.
The created objects have very strange names - like the MAC with some so
urcecode attached, and no signals are set any more.
The names used in 0.1.2 are now extended by the text" function(element){
    return this.indexOf(element) > -1;
};"

![io_a_dash](https://user-images.githubusercontent.com/6260974/27604482-ac8dcaf6-5b79-11e7-9eec-4822ca864682.png)

**Comment by PArns** [comment]
Please attach a screenshot

**Comment by PArns** [comment]
Which version of Node.js are you using?

**Comment by PArns** [comment]
Ok, found the problem ... New version is on it's way
