### ISSUE TITLE
New MAC address range

### ISSUE THREAD

**Issue by TomBoehm** [PArns/ioBroker.amazon-dash#14]
Had to add:
    "FCA667": "Amazon Technologies Inc.",
to manufacturer.js, to find my brand new dash button

**Comment by PArns** [comment]
Please upgrade to the latest version... There is no manufacturer.js any longer and the new range was added 3 Weeks ago ;)

**Comment by TomBoehm** [comment]
Thank you ;-)

**Comment by TomBoehm** [comment]
Please add: "18742E" to MAC Address range's (my new dash is in that range)
