### ISSUE TITLE
Einige Dash Buttons funktionieren nicht.

### ISSUE THREAD

**Issue by vr6syncro** [PArns/ioBroker.amazon-dash#15]
Habe aktuell einen Dash Button der einfach nicht will.

Würde dir gerne mehr Daten zukommen lassen aber weiß nicht wie ich sowas loggen kann

**Comment by vr6syncro** [comment]
Bitte die beiden Mac's hinzufügen:
FC:A6:67:
68:37:E9:

**Comment by PArns** [comment]
FC:A6:67 ist bereits bestandteil (bitte auf die letzte Dev bzw. NPM Version aktualisieren!
Letztere kann ich gerne noch adden

**Comment by sven710** [comment]
Ich habe da noch 2 Buttons die nicht erkannt werden Nummer(sind beide im gleichen Bereich ) :
18:74:2E:

**Comment by PArns** [comment]
Bitte aktualisiere auf die aktuelle Version 0.2.4, die MACs sind schon vor über 1 Monat hinzugefügt worden,
die 2 aus dem letzten Report von vr6yncro heute morgen
