### ISSUE TITLE
New Mac-Family

### ISSUE THREAD

**Issue by Omega236** [PArns/ioBroker.amazon-dash#17]
Hello,

i have a Afri-Cola Dash Button  with Mac 68:37:E9:XX:XX:XX
Could you Add the MAC family?

By the way:
Why is in my IOBroker the newest Version 0.1.2 and not 0.2.4?

**Comment by PArns** [comment]
Hi, I‘m currently on vacation, so it‘ll need a few more days to update ... feel free to add the MAC within the index.js manually! 

The repos are not updated regulary, so you should switch your update path (better to ask at the ioBroker board for further assistance)

**Comment by PArns** [comment]
Added to 0.2.5
