### ISSUE TITLE
Prepare adapter for ioBroker official repo?

### ISSUE THREAD

**Issue by Apollon77** [PArns/ioBroker.amazon-dash#25]
?! :-)

**Comment by Apollon77** [comment]
and activate testig in package.json

**Comment by foxriver76** [comment]
Already in offical repo: https://github.com/ioBroker/ioBroker.repositories/blob/5da3d602294243c8e441da7ac3693a85d720a129/sources-dist-stable.json#L17

But I added a PR to match ioBroker Repo requirements much more.

**Comment by Apollon77** [comment]
It seems i mixed up things ...  too many stuff. Thank you!
