### ISSUE TITLE
Windows 10 Installation

### ISSUE THREAD

**Issue by xmace** [PArns/ioBroker.amazon-dash#29]
Installation in windows Umgebung nicht möglich.

node 8.9.4
npm 4.6.1
`$ ./iobroker add amazon-dash
npm install iobroker.amazon-dash --production --prefix "C:/iobroker" (System call)
Der Befehl "apt-get" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Der Befehl "true" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

npm
 ERR!
 
code
 ELIFECYCLE
npm
 
ERR! 
errno
 1
npm
 
ERR!
 iobroker.amazon-dash@0.2.7 preinstall: `apt-get install libpcap-dev -y || true`
npm
 
ERR! Exit status 1
npm
 ERR!
 
npm
 ERR! Failed at the iobroker.amazon-dash@0.2.7 preinstall script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2018-02-05T23_25_47_039Z-debug.log
host.BRIX-SERVER create instance amazon-dash
ERROR: host.BRIX-SERVER error: reading io-package.json Error: ENOENT: no such file or directory, open 'C:\iobroker\node_modules\iobroker.js-controller\adapter\amazon-dash\io-package.json'
ERROR: process exited with code 20`

**Comment by PArns** [comment]
Sorry aber dieser Adapter ist derzeit nur für Linux
