### ISSUE TITLE
Missing MAC in node_modules/iobroker.amazon-dash/main.js

### ISSUE THREAD

**Issue by RoFrie** [PArns/ioBroker.amazon-dash#31]
Currently the following 6 leading characters of an amazon-Dash MAC are missing in the list of node_modules/iobroker.amazon-dash/main.js
**2C3AE8**
Thx

**Comment by tobintax** [comment]
This one also needs to be added
6c5697

**Comment by PArns** [comment]
Added with the next patch!

THX
