### ISSUE TITLE
Fehler nach Update von Node.js auf V8

### ISSUE THREAD

**Issue by MarkSau** [PArns/ioBroker.amazon-dash#32]
Nach dem Update von Node.js auf v8.10.0 kommen folgende Fehler beim Start von Amazon.dash

amazon-dash.0 | 2018-03-09 11:17:52.247 | info | starting. Version 0.2.8 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v8.10.0
-- | -- | -- | --
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | at Module.load (module.js:565:32)
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | at Object.Module._extensions..js (module.js:663:10)
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | at Module._compile (module.js:652:30)
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | at Object. (/opt/iobroker/node_modules/pcap/pcap.js:3:21)
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | at require (internal/module.js:11:18)
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | at Module.require (module.js:596:17)
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | at Function.Module._load (module.js:497:3)
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | at tryModuleLoad (module.js:505:12)
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | at Module.load (module.js:565:32)
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | at Object.Module._extensions..node (module.js:681:18)
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | the module (for instance, using `npm rebuild` or `npm install`).
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | NODE_MODULE_VERSION 48. This version of Node.js requires
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | was compiled against a different Node.js version using
amazon-dash.0 | 2018-03-09 11:17:51.866 | error | Error: The module '/opt/iobroker/node_modules/pcap/build/Release/pcap_binding.node'
amazon-dash.0 | 2018-03-09 11:17:51.858 | error | the module (for instance, using `npm rebuild` or `npm install`).
amazon-dash.0 | 2018-03-09 11:17:51.858 | error | NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
amazon-dash.0 | 2018-03-09 11:17:51.858 | error | NODE_MODULE_VERSION 48. This version of Node.js requires
amazon-dash.0 | 2018-03-09 11:17:51.858 | error | was compiled against a different Node.js version using
amazon-dash.0 | 2018-03-09 11:17:51.858 | error | uncaught exception: The module '/opt/iobroker/node_modules/pcap/build/Release/pcap_binding.node'

Was kann ich tun? Ausser Downgraden?

**Comment by PArns** [comment]
Hi, wie schon im Log steht:

NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
was compiled against a different Node.js version using

Bitte installiere den Adapter neu oder führe unter deinem Installationsverzeichnis
```
cd ./node_modules/iobroker.amazon-dash/
node-gyp rebuild
```
aus
