### ISSUE TITLE
iobroker.amazon-dash@0.2.8~preinstall: cannot run in wd %s %s (wd=%s)

### ISSUE THREAD

**Issue by PolarQualle** [PArns/ioBroker.amazon-dash#34]
When I try to install the Amazon Dash-Button Adapter in IOBroker, I receive the following error while Installation:

`pi@raspberrypi-iobroker:~ $ sudo npm i iobroker.amazon-dash
npm WARN lifecycle iobroker.amazon-dash@0.2.8~preinstall: cannot run in wd %s %s (wd=%s) iobroker.amazon-dash@0.2.8 apt-get install libpcap-dev -y || true /home/pi/node_modules/.staging/iobroker.amazon-dash-c68c26a5
/home/pi
└── iobroker.amazon-dash@0.2.8 

npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.`

libpcap is installed.

**Comment by PArns** [comment]
Unfotunately, I can't see any errors within this log!

Please install the adapter through the Admin and it should run smoothly

**Comment by PolarQualle** [comment]
I installed it through the Admin plugin, bun unfortunately it doesn't start.

**Comment by PArns** [comment]
Then please post the log file

**Comment by PolarQualle** [comment]
![bildschirmfoto 2018-03-24 um 16 06 57](https://user-images.githubusercontent.com/1499925/37865518-d9575ff6-2f7d-11e8-8990-1293b12c5ab1.png)
![bildschirmfoto 2018-03-24 um 16 07 05](https://user-images.githubusercontent.com/1499925/37865519-d973e50e-2f7d-11e8-822f-771b11c279d9.png)
![bildschirmfoto 2018-03-24 um 16 09 54](https://user-images.githubusercontent.com/1499925/37865520-d98e5984-2f7d-11e8-88e7-9fd2308ccfb2.png)

**Comment by PArns** [comment]
As I said, please run
`apt-get install libpcap-dev`
and reinstall the adapter (remove and install)

Or run from ./node_modules/iobroker.amazon-dash
`node-gyp recompile`

**Comment by PolarQualle** [comment]
I already installed this, but I will try option 2.

**Comment by PolarQualle** [comment]
The `node-gyp recompile` is not available for me.
![bildschirmfoto 2018-03-24 um 16 26 55](https://user-images.githubusercontent.com/1499925/37865670-3334b7e2-2f80-11e8-8b69-199d512bb5ae.png)

When I reinstall the adapter it looks fine for me, right?
![bildschirmfoto 2018-03-24 um 16 25 45](https://user-images.githubusercontent.com/1499925/37865673-40b9e2ca-2f80-11e8-9ff6-4da3450e2385.png)

**Comment by PArns** [comment]
Please use 
**rebuild**

**Comment by PolarQualle** [comment]
![bildschirmfoto 2018-03-24 um 16 46 16](https://user-images.githubusercontent.com/1499925/37865875-e7404650-2f82-11e8-91e6-9e20531c1533.png)

**Comment by foxriver76** [comment]
Node Version 9.8.0 ist keine LTS. Du solltest eine gerade Versionsnummer wählen (z. B. 8)
Ansonsten probier es mal mit `sudo node-gyp rebuild`

**Comment by PArns** [comment]
Closed due to outdated issue. Please update Node!
If this error still persists, please reopen the issue
