### ISSUE TITLE
Ordnerstruktur als Typ-Device erstellen

### ISSUE THREAD

**Issue by StrayDog2205** [PArns/ioBroker.amazon-dash#48]
Es wäre gut, wenn die Ordnerpfade als Geräte erstellt würden.
Grund ist der, das man dann die Ordner passiv benennen kann und so eine bessere Übersicht über seine eingebundenen Geräte hat.

Beispielbild:
![grafik](https://user-images.githubusercontent.com/45132233/48666315-88d34380-eabf-11e8-9aa9-ac88cd7715d3.png)

**Comment by DutchmanNL** [comment]
aggree and very good suggestion, devices folders should be created as device to enable all to set names etc.
See example of other adadpter like homematic which all follow the ame principle

**Comment by DutchmanNL** [comment]
Great thank you !
