### ISSUE TITLE
Anstatt Name steht Macadresse im Feld Name

### ISSUE THREAD

**Issue by Ilovegym66** [PArns/ioBroker.amazon-dash#51]
Neue Version 0.3.0 läuft ohne Probleme hier, nur ein Bug ist mir aufgefallen, dass der Name aus der Konfig den ich eingetragen habe, nicht in das Name Feld des Objektes übernommen wird.

npm 6.4.1, Node 8.14.0, js-controller 1.5.3, linux mint 18.3.

**Comment by foxriver76** [comment]
Das Problem ist, dass es sich nur um eine Angabe einer Mac-Familie handelt. Es kann also durchaus vorkommen, dass du mehre Dash-Buttons mit den gleichen ersten 6 Ziffern der Mac-Adresse hast. Die einzige Möglichkeit, es mit dem aktuellen Adapter Ansatz zu kombinieren, wäre dann eben jedem Dash Button der mit den entsprechenden Ziffern beginnt den Namen zuzuweisen (denke allerdings, dass das keine schöne Lösung ist).

Evtl. wäre langfristig eine Whitelist denkbar (entsprechend der Wünsche anderer Issus), in der man dann komplette Mac Adressen angibt und dann Namen auch genau zuweisen kann.

**Comment by Ilovegym66** [comment]
Hi, ja verstaendlich, denke das mit der Whitelist ist am besten, komplette Mac und Name rein. 
Version 0.3.1 laeuft hier auch ohne Prob.
