### ISSUE TITLE
Can't install - and when it's working - can't create instance

### ISSUE THREAD

**Issue by cm86** [PArns/ioBroker.amazon-dash#55]
Hello,
i can't install the adapter via the webgui...

Hardware: Beelink BT3
OS: Ubuntu Server 18.04 LTS

`$ ./iobroker add amazon-dash  --host iobrokerubuntuserver
NPM version: 6.5.0
npm install iobroker.amazon-dash --production --save --prefix "/opt/iobroker" (System call)

WARNING: apt 
does not have a stable CLI interface. 
Use with caution in scripts.

E: Sperrdatei /var/lib/dpkg/lock-frontend konnte nicht geöffnet werden. - open (13: Permission denied)E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../../../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~

../pcap_session.cc: In static member function ‘static void PcapSession::PacketReady(u_char*, const pcap_pkthdr*, const u_char*)’:../pcap_session.cc:85:102: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(session->packet_ready_cb), 0, NULL);
                                                                                                      ^
In file included from ../pcap_session.h:4:0,
                 from ../pcap_session.cc:7:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~

host.iobrokerubuntuserver install adapter amazon-dash
got /opt/iobroker/node_modules/iobroker.amazon-dash/admin
upload [3] amazon-dash.admin /opt/iobroker/node_modules/iobroker.amazon-dash/admin/words.js words.js application/javascript
upload [2] amazon-dash.admin /opt/iobroker/node_modules/iobroker.amazon-dash/admin/index_m.html index_m.html text/html
upload [1] amazon-dash.admin /opt/iobroker/node_modules/iobroker.amazon-dash/admin/index.html index.html text/html
upload [0] amazon-dash.admin /opt/iobroker/node_modules/iobroker.amazon-dash/admin/amazon-dash.png amazon-dash.png image/png
host.iobrokerubuntuserver object system.adapter.amazon-dash created
host.iobrokerubuntuserver create instance amazon-dash
host.iobrokerubuntuserver object system.adapter.amazon-dash.0.outputCount created
host.iobrokerubuntuserver object system.adapter.amazon-dash.0.inputCount created
host.iobrokerubuntuserver object system.adapter.amazon-dash.0.uptime created
host.iobrokerubuntuserver object system.adapter.amazon-dash.0.memRss created
host.iobrokerubuntuserver object system.adapter.amazon-dash.0.memHeapTotal created
host.iobrokerubuntuserver object system.adapter.amazon-dash.0.memHeapUsed created
host.iobrokerubuntuserver object system.adapter.amazon-dash.0.connected created
host.iobrokerubuntuserver object system.adapter.amazon-dash.0.alive created
host.iobrokerubuntuserver object system.adapter.amazon-dash.0 created
process exited with code 0`

if i do this over the console...
`ioBroker add amazon-dash`
i get this:
`NPM version: 6.5.0
npm install iobroker.amazon-dash --production --save --prefix "/opt/iobroker" (System call)

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Sperrdatei /var/lib/dpkg/lock-frontend konnte nicht geöffnet werden. - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/pcap/node_modules/socketwatcher/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/iobroker/node_modules/pcap/node_modules/socketwatcher/.node-gyp'
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/pcap/node_modules/socketwatcher
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! socketwatcher@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the socketwatcher@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-02T21_28_09_325Z-debug.log`

here the last lines of the log say...
`135 verbose stack Error: socketwatcher@0.3.0 install: `node-gyp rebuild`
135 verbose stack Exit status 1
135 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
135 verbose stack     at emitTwo (events.js:126:13)
135 verbose stack     at EventEmitter.emit (events.js:214:7)
135 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
135 verbose stack     at emitTwo (events.js:126:13)
135 verbose stack     at ChildProcess.emit (events.js:214:7)
135 verbose stack     at maybeClose (internal/child_process.js:915:16)
135 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
136 verbose pkgid socketwatcher@0.3.0
137 verbose cwd /root
138 verbose Linux 4.15.0-43-generic
139 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.amazon-dash" "--production" "--save" "--prefix" "/opt/iobroker"
140 verbose node v8.15.0
141 verbose npm  v6.5.0
142 error code ELIFECYCLE
143 error errno 1
144 error socketwatcher@0.3.0 install: `node-gyp rebuild`
144 error Exit status 1
145 error Failed at the socketwatcher@0.3.0 install script.
145 error This is probably not a problem with npm. There is likely additional logging output above.
146 verbose exit [ 1, true ]
`

What could i do to fix this...

Mit freundlichen Grüßen
Chris

**Comment by cm86** [comment]
forgotten:

git is installed...
npm -v
6.5.0
node -v
v8.15.0

**Comment by foxriver76** [comment]
Please use information from https://forum.iobroker.net/viewtopic.php?f=8&t=19209

**Comment by Apollon77** [comment]
check 1.1.0
