### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by denjo82** [PArns/ioBroker.amazon-dash#58]
a new installation with the new installation method of iobroker will result in this error message:

E
: 
Sperrdatei /var/lib/dpkg/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung)E: Sperren des Administrationsverzeichnisses (/var/lib/dpkg/) nicht möglich, sind Sie root?

**Comment by CKMartens** [comment]
Same here. I installed ioBroker on an new installed Ubuntu 18.04 with the new installation documents. At the install ob the adapter this errormessage comes:

```
$ ./iobroker add amazon-dash  --host iobroker
NPM version: 6.4.1
npm install iobroker.amazon-dash --production --save --prefix "/opt/iobroker" (System call)
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


E: Sperrdatei /var/lib/dpkg/lock-frontend konnte nicht geöffnet werden. - open (13: Keine Berechtigung)E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~

../pcap_binding.cc:2:10: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden #include <pcap/pcap.h>
          ^~~~~~~~~~~~~
compilation terminated.

make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

gyp ERR! System Linux 4.15.0-43-genericgyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/pcap
gyp ERR! node -v v8.15.0
gyp
 ERR! node-gyp -v v3.8.0gyp ERR! not ok 

npm
 WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

npm
 ERR! code ELIFECYCLEnpm ERR! errno 1

npm ERR! pcap@2.1.0 install: `node-gyp rebuild`npm ERR! Exit status 1

npm ERR! npm ERR! Failed at the pcap@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-01-14T13_01_18_002Z-debug.log

host.iobroker install adapter amazon-dash
NPM version: 6.4.1
npm install iobroker.amazon-dash --production --save --prefix "/opt/iobroker" (System call)
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


E: Sperrdatei /var/lib/dpkg/lock-frontend konnte nicht geöffnet werden. - open (13: Keine Berechtigung)E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~

../pcap_binding.cc:2:10: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden #include <pcap/pcap.h>
          ^~~~~~~~~~~~~
compilation terminated.

make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
gyp
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! 
stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

gyp ERR! System Linux 4.15.0-43-genericgyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/pcap
gyp ERR! node -v v8.15.0
gyp
 ERR! node-gyp -v v3.8.0gyp ERR! not ok 

npm WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1npm ERR! pcap@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2019-01-14T13_01_45_554Z-debug.log

host.iobroker install adapter amazon-dash
NPM version: 6.4.1
npm install iobroker.amazon-dash --production --save --prefix "/opt/iobroker" (System call)
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


E: Sperrdatei /var/lib/dpkg/lock-frontend konnte nicht geöffnet werden. - open (13: Keine Berechtigung)E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~

../pcap_binding.cc:2:10: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden #include <pcap/pcap.h>
          ^~~~~~~~~~~~~
compilation terminated.

make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
gyp
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp 
ERR! stack     at emitTwo (events.js:126:13)gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/pcap
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR!
 not ok 
npm WARN
 svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

npm 
ERR! code ELIFECYCLEnpm ERR! errno 1

npm ERR! pcap@2.1.0 install: `node-gyp rebuild`npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-01-14T13_02_14_833Z-debug.log

host.iobroker install adapter amazon-dash
ERROR: host.iobroker Cannot install amazon-dash
ERROR: process exited with code 13
```

**Comment by ltsalvatore** [comment]
i've got the same problem that i can not install amazon-dash on a debian system, which is on a proxmox server.

on my first attempt i encountered this error: **Fertig mit Fehler: host.shsrv Cannot install amazon-dash**
`$ ./iobroker add amazon-dash  --host shsrv
NPM version: 6.4.1
npm install iobroker.amazon-dash --production --save --prefix "/opt/iobroker" (System call)

WARNING: 
apt
 
does not have a stable CLI interface. 
Use with caution in scripts.


E
: 
Sperrdatei /var/lib/dpkg/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung)

E
: 
Sperren des Administrationsverzeichnisses (/var/lib/dpkg/) nicht möglich, sind Sie root?

../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^

In file included from ../socket_watcher.hpp:8:0,                 from ../socket_watcher.cpp:5:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~

../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden #include <pcap/pcap.h>
                       ^

compilation terminated.
make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Fehler 1gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/pcap
gyp
 ERR! node -v v8.15.0gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

npm
 
ERR!
 
code
 ELIFECYCLE
npm
 
ERR!
 
errno
 1
npm
 
ERR!
 pcap@2.1.0 install: `node-gyp rebuild`
npm
 
ERR!
 Exit status 1
npm
 ERR! npm ERR!
 Failed at the pcap@2.1.0 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm
 
ERR!
 A complete log of this run can be found in:
npm
 
ERR!
     /home/iobroker/.npm/_logs/2019-01-17T18_36_18_665Z-debug.log
host.shsrv install adapter amazon-dash
NPM version: 6.4.1npm install iobroker.amazon-dash --production --save --prefix "/opt/iobroker" (System call)


WARNING: 
apt
 
does not have a stable CLI interface. 
Use with caution in scripts.


E
: 
Sperrdatei /var/lib/dpkg/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung)

E
: 
Sperren des Administrationsverzeichnisses (/var/lib/dpkg/) nicht möglich, sind Sie root?

../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^

In file included from ../socket_watcher.hpp:8:0,                 from ../socket_watcher.cpp:5:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~

../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden #include <pcap/pcap.h>
                       ^

compilation terminated.
make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Fehler 1gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/pcap
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

npm
 
ERR!
 
code
 ELIFECYCLE
npm
 
ERR!
 
errno
 1
npm
 
ERR!
 pcap@2.1.0 install: `node-gyp rebuild`
npm
 
ERR!
 Exit status 1
npm
 ERR! npm ERR! Failed at the pcap@2.1.0 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm
 
ERR!
 A complete log of this run can be found in:
npm
 
ERR!
     /home/iobroker/.npm/_logs/2019-01-17T18_36_26_041Z-debug.log
host.shsrv install adapter amazon-dash
NPM version: 6.4.1npm install iobroker.amazon-dash --production --save --prefix "/opt/iobroker" (System call)


WARNING: 
apt
 
does not have a stable CLI interface. 
Use with caution in scripts.


E
: 
Sperrdatei /var/lib/dpkg/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung)

E
: 
Sperren des Administrationsverzeichnisses (/var/lib/dpkg/) nicht möglich, sind Sie root?

../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^

In file included from ../socket_watcher.hpp:8:0,                 from ../socket_watcher.cpp:5:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~

../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden #include <pcap/pcap.h>
                       ^

compilation terminated.
make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Fehler 1gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/pcap
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0

gyp
 
ERR!
 
not ok
 
npm
 
ERR!
 
code
 ELIFECYCLE
npm
 
ERR!
 
errno
 1
npm
 
ERR!
 pcap@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1npm
 ERR! npm
 ERR! Failed at the pcap@2.1.0 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm
 
ERR!
 A complete log of this run can be found in:
npm
 
ERR!
     /home/iobroker/.npm/_logs/2019-01-17T18_36_33_546Z-debug.log
host.shsrv install adapter amazon-dash
ERROR: host.shsrv Cannot install amazon-dash
ERROR: process exited with code 13`

my second attempt after having installed libpcap-dev as described on the adapters info page allowed me to install the adapter, but now i have permanent error messages in the iobroker log and still no connection

`

host.shsrv | 2019-01-18 13:57:42.318 | error | instance system.adapter.amazon-dash.0 terminated with code 0 (OK)
-- | -- | -- | --
host.shsrv | 2019-01-18 13:57:42.318 | error | Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:787:25)
host.shsrv | 2019-01-18 13:57:42.318 | error | Caught by controller[0]: at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:748:13)
host.shsrv | 2019-01-18 13:57:42.318 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29
host.shsrv | 2019-01-18 13:57:42.318 | error | Caught by controller[0]: at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)
host.shsrv | 2019-01-18 13:57:42.318 | error | Caught by controller[0]: at Adapter.emit (events.js:208:7)
host.shsrv | 2019-01-18 13:57:42.318 | error | Caught by controller[0]: at emitNone (events.js:106:13)
host.shsrv | 2019-01-18 13:57:42.318 | error | Caught by controller[0]: at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:43:5)
host.shsrv | 2019-01-18 13:57:42.318 | error | Caught by controller[0]: at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:78:29)
host.shsrv | 2019-01-18 13:57:42.318 | error | Caught by controller[0]: at Object.exports.createSession (/opt/iobroker/node_modules/pcap/pcap.js:123:12)
host.shsrv | 2019-01-18 13:57:42.318 | error | Caught by controller[0]: at new PcapSession (/opt/iobroker/node_modules/pcap/pcap.js:49:39)
host.shsrv | 2019-01-18 13:57:42.317 | error | Caught by controller[0]: Error: socket: Operation not permitted
`

**Comment by nexxx** [comment]
I am facing the same issue. 
Fresh installation due to move from RPI3 to XU4.

**Comment by nob0dy80** [comment]
really guys? why are you  running linux systems if you cant simple permission errors..

**Comment by ltsalvatore** [comment]
> really guys? why are you running linux systems if you cant fix simple permission errors..

because not everyone is that fucking smart like you are.

**Comment by nob0dy80** [comment]
and now you think you can top that with a even more dumber answer?

**Comment by nob0dy80** [comment]
well.. use the shell to fix the permission as root .. if you got any more problems..just install the adapter over commandline as root... end of story.

**Comment by ltsalvatore** [comment]
> and now you think you can top that with a even more dumber answer?

sorry.. shouldn’t come over that rude. a smile would have been appropriate. 

at least you recognized by yourself that your answer was kind of "dumb".  :-P

anyway.. 
thanks for your more helpful answer 👍

**Comment by nob0dy80** [comment]
@ltsalvatore 
cause you said sory.. some more infos for your
login as root, do cd /opt/iobroker
be sure you have pcap dev installed before (apt-get install libpcap-dev)
do setcap cap_net_raw+eip $(eval readlink -f `which node`)
do npm i https://github.com/PArns/ioBroker.amazon-dash/tarball/master --production
do iobroker upload amazon-dash
than go back to adapter mask and push the + symbol to add the adapter..

everything should be fine now

**Comment by ltsalvatore** [comment]
thank you nob0dy80, 

will give it a go later. 👍

**Comment by nob0dy80** [comment]
@ltsalvatore 
you're welcome

**Comment by Apollon77** [comment]
Please use the installation Fixer (der forum announcements) in your system and after this the problem should be gone. If not please open comment again.

**Comment by nob0dy80** [comment]
@Apollon77 
really sad if this is needed on an installation that is made today.

**Comment by nob0dy80** [comment]
@ltsalvatore 
if its an old iobroker installation, @Apollon77  should be right trying at first the fix script.

**Comment by Apollon77** [comment]
Ok, if the installation was made today then it should not be needed becauseinstaller and fixer are in sync

**Comment by Apollon77** [comment]
@nob0dy80 then please provide YOUR log!

**Comment by nob0dy80** [comment]
@Apollon77 
sure, where is it logged? not seeing this errors in the /opt/iobroker/log files

**Comment by Apollon77** [comment]
But should be there

**Comment by nob0dy80** [comment]
ok seems like i killed it..but is see something that is close to this in my log

019-03-12 19:41:05.477  - [32minfo[39m: host.iobrokerM Update repository "default" under "http://download.iobroker.net/sources-dist.json"
2019-03-12 19:41:13.471  - [32minfo[39m: iobroker add alexa2  --host iobrokerM
2019-03-12 19:41:13.664  - [32minfo[39m: iobroker host.iobrokerM install adapter alexa2
2019-03-12 19:41:13.818  - [32minfo[39m: iobroker npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.alexa2"
2019-03-12 19:41:18.636  - [32minfo[39m: iobroker npm
2019-03-12 19:41:18.636  - [32minfo[39m: iobroker  WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.alexa2
2019-03-12 19:41:18.852  - [32minfo[39m: iobroker npm
2019-03-12 19:41:18.852  - [32minfo[39m: iobroker  ERR! path /opt/iobroker/node_modules/iobroker.alexa2npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

2019-03-12 19:41:18.854  - [32minfo[39m: iobroker npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.alexa2'npm ERR!  { Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.alexa2'

2019-03-12 19:41:18.854  - [32minfo[39m: iobroker npm ERR!   stack: 'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.alexa2\'',npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',

2019-03-12 19:41:18.854  - [32minfo[39m: iobroker npm ERR!   path: '/opt/iobroker/node_modules/iobroker.alexa2' }npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm
2019-03-12 19:41:18.855  - [32minfo[39m: iobroker  ERR! It is likely you do not have the permissions to access this file as the current usernpm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running

2019-03-12 19:41:18.855  - [32minfo[39m: iobroker npm ERR! the command again as root/Administrator (though this is not recommended).
2019-03-12 19:41:18.893  - [32minfo[39m: iobroker npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2019-03-12T18_41_18_861Z-debug.log

2019-03-12 19:41:18.901  - [32minfo[39m: iobroker Cannot install iobroker.alexa2: 243


i think dash acted the same way....

**Comment by nob0dy80** [comment]
since the system i only one user and not handling any other as iobroker, if fixed it quick and dirty with chmod.

**Comment by Apollon77** [comment]
check 1.1.0
