### ISSUE TITLE
How to setup Dash Button Adapter without iobroker running as root

### ISSUE THREAD

**Issue by mikepiko** [PArns/ioBroker.amazon-dash#61]
Hey, not an issue, but it could be useful for others whom want to use the adapter with newer Version of iobroker which do not run as "root" anymore.

You´ll need to set permissions to nodejs to run libpcap without root permissions.

in my case nodejs was installed in /usr/bin/node
so the command to use was:

setcap cap_net_raw,cap_net_admin=eip /usr/bin/node

Maybe you´ll put it in the help section of the Adapter.

**Comment by Bluelightcrew** [comment]
Thanks! That helps me a lot.
