### ISSUE TITLE
Adapter does not work with Node.js v10

### ISSUE THREAD

**Issue by ProfMertes** [PArns/ioBroker.amazon-dash#66]
After updating Node.js from v8.17.0 to v10.18 the adapter won't build successfully.

**Comment by DutchmanNL** [comment]
is i. worth maintaining this adapter I hough these buttons don't work anymore

**Comment by ProfMertes** [comment]
It is 100% worth to maintain this adapter. With Node.js version v.8 or below it works pefectly for me. Maybe you have Node.js v10 or higher.

**Comment by paulchen007** [comment]
same here. after update to node.js v10 the adapter will not recognize a button-press :(

**Comment by Ilovegym66** [comment]
works here fine with node10.x, have you start the iobroker-fixer after update the node-version?

**Comment by paulchen007** [comment]
yip. iobroker-fixer executed. dash-button is not working.

**Comment by ProfMertes** [comment]
same here. iobroker-fixer did not fix the problem with node.js v10. dash-button still does not work.

**Comment by daniel-lo** [comment]
Is this also a node.js thing?

`

amazon-dash.0 | 2020-01-26 08:20:07.727 | error | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
-- | -- | -- | --
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | at client.keys (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:684:17)
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | at states.getKeys (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6811:25)
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | at initLogging (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:7114:22)
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | at Adapter.emit (events.js:198:13)
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:43:5)
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:78:29)
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | at Object.exports.createSession (/opt/iobroker/node_modules/pcap/pcap.js:123:12)
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | at new PcapSession (/opt/iobroker/node_modules/pcap/pcap.js:49:39)
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | (16696) Error: socket: Operation not permitted
amazon-dash.0 | 2020-01-26 08:20:07.727 | error | (16696) uncaught exception: socket: Operation not permitted

`

**Comment by daniel-lo** [comment]
installation fixer seems to have remedied .. logfile looks quiet (for the moment)

**Comment by Apollon77** [comment]
Please check my fork https://github.com/Apollon77/ioBroker.amazon-dash 1.0.1

**Comment by ProfMertes** [comment]
awesome dude, thx

unfortunately:
host.iobroker	2020-02-24 21:37:56.244	info	Restart adapter system.adapter.amazon-dash.0 because enabled
host.iobroker	2020-02-24 21:37:56.243	error	instance system.adapter.amazon-dash.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker	2020-02-24 21:37:56.243	error	Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.iobroker	2020-02-24 21:37:56.243	error	Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.iobroker	2020-02-24 21:37:56.243	error	Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.iobroker	2020-02-24 21:37:56.242	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/pcap/pcap.js:3:21)
host.iobroker	2020-02-24 21:37:56.242	error	Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.iobroker	2020-02-24 21:37:56.242	error	Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.iobroker	2020-02-24 21:37:56.242	error	Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.iobroker	2020-02-24 21:37:56.242	error	Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.iobroker	2020-02-24 21:37:56.241	error	Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.iobroker	2020-02-24 21:37:56.241	error	Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
host.iobroker	2020-02-24 21:37:56.241	error	Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.iobroker	2020-02-24 21:37:56.241	error	Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
host.iobroker	2020-02-24 21:37:56.240	error	Caught by controller[0]: NODE_MODULE_VERSION 57. This version of Node.js requires
host.iobroker	2020-02-24 21:37:56.240	error	Caught by controller[0]: was compiled against a different Node.js version using
host.iobroker	2020-02-24 21:37:56.239	error	Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/pcap/build/Release/pcap_binding.node'
amazon-dash.0	2020-02-24 21:37:55.705	warn	(1902) Terminated (UNCAUGHT_EXCEPTION): Without reason
amazon-dash.0	2020-02-24 21:37:55.485	info	(1902) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v10.19.0
host.iobroker	2020-02-24 21:37:53.293	info	instance system.adapter.amazon-dash.0 started with pid 1902

**Comment by Apollon77** [comment]
Can ypu show the installation log please? Do you installed the adapter and updated nodejs afterwards? Please go to /opt/iobroker/node_modules/pcap/ and execute "npm rebuild"

Try after that again

**Comment by ProfMertes** [comment]
yes i updated your package first to 1.0.1 and updated afterwards node.js from 8.17 to 10.19
npm rebuild gets me:
nan@2.14.0 /opt/iobroker/node_modules/pcap/node_modules/nan

**Comment by Apollon77** [comment]
And what is the output of the npm rebuild command itself?
And in fact it was completely the wrong order :-) You need to do some additional stept when you update nodejs major versions!

or ok different:
cd /opt/iobroker/node_modules/iobroker.amazon-dash
npm install

**Comment by ProfMertes** [comment]
how it worked though:
  apt-get update
  apt-get install libpcap-dev
  iobroker add amazon-dash
  iobroker start
As it seems libpcap caused the problem. Thanks for your support!
