### ISSUE TITLE
Problems after restore on other machine

### ISSUE THREAD

**Issue by daniel-lo** [PArns/ioBroker.amazon-dash#70]
Hi, after restoring my config on another machine I have problems with this adapter. Pls help.

amazon-dash.0 | 2020-04-27 05:06:53.213 | warn | (2518) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
-- | -- | -- | --
amazon-dash.0 | 2020-04-27 05:06:53.159 | error | (2518) adapter disabled
amazon-dash.0 | 2020-04-27 05:06:21.503 | info | (1797) Terminated (NO_ERROR): Without reason
amazon-dash.0 | 2020-04-27 05:06:21.502 | info | (1797) terminating
amazon-dash.0 | 2020-04-27 05:06:21.464 | info | (1797) cleaned everything up...
amazon-dash.0 | 2020-04-27 05:06:21.462 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
amazon-dash.0 | 2020-04-27 05:06:21.462 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8064:34
amazon-dash.0 | 2020-04-27 05:06:21.462 | error | at Adapter.emit (events.js:310:20)
amazon-dash.0 | 2020-04-27 05:06:21.462 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:53:9)
amazon-dash.0 | 2020-04-27 05:06:21.462 | error | at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:90:29)
amazon-dash.0 | 2020-04-27 05:06:21.462 | error | at Object.exports.createSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:131:12)
amazon-dash.0 | 2020-04-27 05:06:21.462 | error | at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:60:39)
amazon-dash.0 | 2020-04-27 05:06:21.462 | error | (1797) Error: socket: Operation not permitted
amazon-dash.0 | 2020-04-27 05:06:21.459 | error | (1797) uncaught exception: socket: Operation not permitted
amazon-dash.0 | 2020-04-27 05:06:21.450 | info | (1797) starting pcap session on default interface
amazon-dash.0 | 2020-04-27 05:06:21.431 | info | (1797) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v12.16.2, js-controller: 3.0.19
amazon-dash.0 | 2020-04-27 05:05:49.751 | info | (1037) Terminated (NO_ERROR): Without reason
amazon-dash.0 | 2020-04-27 05:05:49.750 | info | (1037) terminating
amazon-dash.0 | 2020-04-27 05:05:49.700 | info | (1037) cleaned everything up...
amazon-dash.0 | 2020-04-27 05:05:49.699 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
amazon-dash.0 | 2020-04-27 05:05:49.699 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8064:34
amazon-dash.0 | 2020-04-27 05:05:49.699 | error | at Adapter.emit (events.js:310:20)
amazon-dash.0 | 2020-04-27 05:05:49.699 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:53:9)
amazon-dash.0 | 2020-04-27 05:05:49.699 | error | at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:90:29)
amazon-dash.0 | 2020-04-27 05:05:49.699 | error | at Object.exports.createSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:131:12)
amazon-dash.0 | 2020-04-27 05:05:49.699 | error | at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:60:39)
amazon-dash.0 | 2020-04-27 05:05:49.699 | error | (1037) Error: socket: Operation not permitted
amazon-dash.0 | 2020-04-27 05:05:49.690 | error | (1037) uncaught exception: socket: Operation not permitted
amazon-dash.0 | 2020-04-27 05:05:49.688 | info | (1037) starting pcap session on default interface
amazon-dash.0 | 2020-04-27 05:05:49.669 | info | (1037) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v12.16.2, js-controller: 3.0.19
amazon-dash.0 | 2020-04-27 05:05:18.020 | info | (316) Terminated (NO_ERROR): Without reason
amazon-dash.0 | 2020-04-27 05:05:18.019 | info | (316) terminating
amazon-dash.0 | 2020-04-27 05:05:17.980 | info | (316) cleaned everything up...

**Comment by Ilovegym66** [comment]
"iobroker fix" 
is your friend :-)

**Comment by daniel-lo** [comment]
already did so .. didn't help

**Comment by Apollon77** [comment]
Csn you please show the output of the fix command?

**Comment by daniel-lo** [comment]
![fix](https://user-images.githubusercontent.com/4311558/80355089-ea344000-8877-11ea-8d0a-b71f517d9dbe.png)

**Comment by Apollon77** [comment]
Ok looks correct. and it stiull do not work?

**Comment by daniel-lo** [comment]
no

**Comment by Apollon77** [comment]
Ok was sagt 

```
sudo getcap $(eval readlink -f `which node`)
```

**Comment by daniel-lo** [comment]
/home/<usr>/.nvm/versions/node/v12.16.2/bin/node = cap_net_bind_service,cap_net_admin,cap_net_raw+eip

**Comment by daniel-lo** [comment]
nachdem ich node und nodejs gedowngraded hab hab ich nun alle meine Adapterprobleme gelöst .. grad hab ich noch dash zum laufen gebracht über:

npm i --production
npm audit fix

**Comment by Apollon77** [comment]
Audit fix eigentlich ein no Go bzw danach kann niemand mehr sagen ob noch alles tut. Aber ok. 

Nodejs 10 hat noch bis April 2021 support.

**Comment by daniel-lo** [comment]
April 2021 ist ja noch ne Weile hin .. muss ich jetzt davon ausgehen, dass mir dann die Adapter um die Ohren fliegen?

**Comment by Apollon77** [comment]
Uuuiii was sehe ich da ... nvm?! Ich bin mir nicht sicher in wieweit iobroker wirlich nvm unterstützt ... nicht das er ein anderes nodejs executable starte ... läuft ja alles unter dem User iobroker und nicht unter deinem. Das wäre wenn ein eigenes Forum Thread wert!

**Comment by daniel-lo** [comment]
wo soll ich den denn eröffnen .. wenn ich was böses gemacht hab würde ich das gerne korrigieren .. allerdings bräuchte ich dabei Hilfestellung

**Comment by Apollon77** [comment]
naja "böse" ist relativ. Mein "tipp" ist das die executable für die du die setcap rechte setzt irgendwie ne andere ist als die von ioBroker verwendet wird.
Im Forum nen Thread auf machen weil mit nvm bin ich am Ende ... aber wir wissen das es mit setcap generell tut, also wäre das jetzt erstmal die wahrscheinlichste veriante

**Comment by daniel-lo** [comment]
ok .. danke .. das heb ich mir aber auf .. aktuell funktioniert ja alles.
