### ISSUE TITLE
Socket Operation not permitted

### ISSUE THREAD

**Issue by daniel-lo** [PArns/ioBroker.amazon-dash#73]
Alles etwas fragil .. irgendwas hat mein Dash-Adapter jetzt wieder umgehauen .. gab da irgendein Socket-Adapter-Update .. eventuell deshalb?

amazon-dash.0 | 2020-07-25 19:56:21.761 | info | (6124) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
amazon-dash.0 | 2020-07-25 19:56:21.760 | info | (6124) terminating
amazon-dash.0 | 2020-07-25 19:56:21.735 | info | (6124) cleaned everything up...
amazon-dash.0 | 2020-07-25 19:56:21.735 | error | (6124) Error: socket: Operation not permitted     at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:60:39)     at Object.exports.createSession (/opt/iobroke
amazon-dash.0 | 2020-07-25 19:56:21.733 | error | (6124) unhandled promise rejection: socket: Operation not permitted
amazon-dash.0 | 2020-07-25 19:56:21.733 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
amazon-dash.0 | 2020-07-25 19:56:21.730 | info | (6124) starting pcap session on default interface
amazon-dash.0 | 2020-07-25 19:56:21.714 | info | (6124) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v10.22.0, js-controller: 3.1.6
host.iobroker | 2020-07-25 19:56:20.538 | info | instance system.adapter.amazon-dash.0 started with pid 6124
host.iobroker | 2020-07-25 19:55:50.531 | info | Restart adapter system.adapter.amazon-dash.0 because enabled
host.iobroker | 2020-07-25 19:55:50.530 | info | instance system.adapter.amazon-dash.0 terminated with code 0 (NO_ERROR)
amazon-dash.0 | 2020-07-25 19:55:50.015 | info | (5386) Terminated (NO_ERROR): Without reason
amazon-dash.0 | 2020-07-25 19:55:50.014 | info | (5386) terminating
amazon-dash.0 | 2020-07-25 19:55:49.990 | info | (5386) cleaned everything up...
amazon-dash.0 | 2020-07-25 19:55:49.989 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
amazon-dash.0 | 2020-07-25 19:55:49.989 | error | at promiseReadSecret.then.then (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8148:34)
amazon-dash.0 | 2020-07-25 19:55:49.989 | error | at Adapter.emit (events.js:198:13)
amazon-dash.0 | 2020-07-25 19:55:49.989 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:53:9)
amazon-dash.0 | 2020-07-25 19:55:49.989 | error | at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:90:29)
amazon-dash.0 | 2020-07-25 19:55:49.989 | error | at Object.exports.createSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:131:12)
amazon-dash.0 | 2020-07-25 19:55:49.989 | error | at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:60:39)
amazon-dash.0 | 2020-07-25 19:55:49.989 | error | (5386) Error: socket: Operation not permitted
amazon-dash.0 | 2020-07-25 19:55:49.988 | error | (5386) unhandled promise rejection: socket: Operation not permitted
Unhandled | 2020-07-25 19:55:49.988 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
amazon-dash.0 | 2020-07-25 19:55:49.985 | info | (5386) starting pcap session on default interface
amazon-dash.0 | 2020-07-25 19:55:49.963 | info | (5386) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v10.22.0, js-controller: 3.1.6

**Comment by Apollon77** [comment]
Please run „iobroker fix“. Maybe you did a nodejs update? Then some rights are missing.

**Comment by daniel-lo** [comment]
I had already done that before I reported

**Comment by daniel-lo** [comment]
Mir fällt grad auf, dass sich meine node Version geändert hat. Liegt vermutlich daran .. ble-Adapter versagt auch .. muss ich wieder von 14 auf 10.22 downgraden .. schon wieder befehle suchen :-(

**Comment by Apollon77** [comment]
Äääähhhmm ... also ein node 10-> 14 Update passiert an sich nicht mal eben so .... 

Bitte hier mal Adapter neu installieren bzw die Anleitungen für rebuild nutzen - siehe Forum

Und gg nochmal fixer ausführen!!

**Comment by daniel-lo** [comment]
14 wird angezeigt obwohl 10.22 installiert ist .. da muss ich wohl mal aufräumen .. das wichtigste läuft ja erstmal

**Comment by daniel-lo** [comment]
Alles wieder gut .. hatte mir zusätzlich die 14 installiert als ich diesen Fehler beheben wollte: 

N/A: version "N/A -> N/A" is not yet installed.
You need to run "nvm install N/A" to install it before using it.

14 deinstalliert und "nvm install 10.22.0" ausgeführt .. scheint alles geheilt zu haben .. Adapter wieder grün.
