### ISSUE TITLE
Short green flash - then red

### ISSUE THREAD

**Issue by daniel-lo** [PArns/ioBroker.amazon-dash#76]
Amazing .. this is the only adapter I really frequently have problems with. This time I cannot cure by reinstalling nor by iobroker fixing. Crazy:

amazon-dash.0 | 2021-02-10 13:45:33.496 | warn | (14745) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
amazon-dash.0 | 2021-02-10 13:45:33.496 | info | (14745) terminating
amazon-dash.0 | 2021-02-10 13:45:33.495 | info | (14745) cleaned everything up...
amazon-dash.0 | 2021-02-10 13:45:33.447 | error | (14745) socket: Operation not permitted
amazon-dash.0 | 2021-02-10 13:45:33.447 | error | at promiseReadSecret.then.then (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8479:34)
amazon-dash.0 | 2021-02-10 13:45:33.447 | error | at Adapter.emit (events.js:198:13)
amazon-dash.0 | 2021-02-10 13:45:33.447 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:53:9)
amazon-dash.0 | 2021-02-10 13:45:33.447 | error | at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:90:29)
amazon-dash.0 | 2021-02-10 13:45:33.447 | error | at Object.exports.createSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:131:12)
amazon-dash.0 | 2021-02-10 13:45:33.447 | error | at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:60:39)
amazon-dash.0 | 2021-02-10 13:45:33.447 | error | (14745) Error: socket: Operation not permitted
amazon-dash.0 | 2021-02-10 13:45:33.445 | error | (14745) unhandled promise rejection: socket: Operation not permitted
amazon-dash.0 | 2021-02-10 13:45:33.445 | error | (14745) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
amazon-dash.0 | 2021-02-10 13:45:33.442 | info | (14745) starting pcap session on default interface
amazon-dash.0 | 2021-02-10 13:45:33.441 | debug | (14745) manual MAC : 26
amazon-dash.0 | 2021-02-10 13:45:33.424 | info | (14745) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v10.23.3, js-controller: 3.2.16
amazon-dash.0 | 2021-02-10 13:45:33.234 | debug | (14745) statesDB connected
amazon-dash.0 | 2021-02-10 13:45:33.233 | debug | (14745) States connected to redis: 127.0.0.1:9000
amazon-dash.0 | 2021-02-10 13:45:33.186 | debug | (14745) States create User PubSub Client
amazon-dash.0 | 2021-02-10 13:45:33.185 | debug | (14745) States create System PubSub Client
amazon-dash.0 | 2021-02-10 13:45:33.179 | debug | (14745) Redis States: Use Redis connection: 127.0.0.1:9000
amazon-dash.0 | 2021-02-10 13:45:33.177 | debug | (14745) objectDB connected
amazon-dash.0 | 2021-02-10 13:45:33.171 | debug | (14745) Objects connected to redis: 127.0.0.1:9001
amazon-dash.0 | 2021-02-10 13:45:33.160 | debug | (14745) Objects client initialize lua scripts
amazon-dash.0 | 2021-02-10 13:45:33.160 | debug | (14745) Objects create User PubSub Client
amazon-dash.0 | 2021-02-10 13:45:33.159 | debug | (14745) Objects create System PubSub Client
amazon-dash.0 | 2021-02-10 13:45:33.157 | debug | (14745) Objects client ready ... initialize now
amazon-dash.0 | 2021-02-10 13:45:33.133 | debug | (14745) Redis Objects: Use Redis connection: 127.0.0.1:9001
amazon-dash.0 | 2021-02-10 13:45:01.763 | warn | (13990) Terminated (UNCAUGHT_EXCEPTION): Without reason
amazon-dash.0 | 2021-02-10 13:45:01.763 | info | (13990) terminating
amazon-dash.0 | 2021-02-10 13:45:01.762 | info | (13990) cleaned everything up...
amazon-dash.0 | 2021-02-10 13:45:01.706 | error | (13990) socket: Operation not permitted
amazon-dash.0 | 2021-02-10 13:45:01.705 | error | at promiseReadSecret.then.then (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8479:34)
amazon-dash.0 | 2021-02-10 13:45:01.705 | error | at Adapter.emit (events.js:198:13)
amazon-dash.0 | 2021-02-10 13:45:01.705 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:53:9)
amazon-dash.0 | 2021-02-10 13:45:01.705 | error | at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:90:29)
amazon-dash.0 | 2021-02-10 13:45:01.705 | error | at Object.exports.createSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:131:12)
amazon-dash.0 | 2021-02-10 13:45:01.705 | error | at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:60:39)
amazon-dash.0 | 2021-02-10 13:45:01.705 | error | (13990) Error: socket: Operation not permitted
amazon-dash.0 | 2021-02-10 13:45:01.704 | error | (13990) unhandled promise rejection: socket: Operation not permitted
amazon-dash.0 | 2021-02-10 13:45:01.703 | error | (13990) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
amazon-dash.0 | 2021-02-10 13:45:01.701 | info | (13990) starting pcap session on default interface
amazon-dash.0 | 2021-02-10 13:45:01.700 | debug | (13990) manual MAC : 26
amazon-dash.0 | 2021-02-10 13:45:01.684 | info | (13990) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v10.23.3, js-controller: 3.2.16
amazon-dash.0 | 2021-02-10 13:45:01.520 | debug | (13990) statesDB connected
amazon-dash.0 | 2021-02-10 13:45:01.519 | debug | (13990) States connected to redis: 127.0.0.1:9000
amazon-dash.0 | 2021-02-10 13:45:01.508 | debug | (13990) States create User PubSub Client
amazon-dash.0 | 2021-02-10 13:45:01.508 | debug | (13990) States create System PubSub Client
amazon-dash.0 | 2021-02-10 13:45:01.500 | debug | (13990) Redis States: Use Redis connection: 127.0.0.1:9000
amazon-dash.0 | 2021-02-10 13:45:01.498 | debug | (13990) objectDB connected
amazon-dash.0 | 2021-02-10 13:45:01.491 | debug | (13990) Objects connected to redis: 127.0.0.1:9001
amazon-dash.0 | 2021-02-10 13:45:01.480 | debug | (13990) Objects client initialize lua scripts
amazon-dash.0 | 2021-02-10 13:45:01.479 | debug | (13990) Objects create User PubSub Client
amazon-dash.0 | 2021-02-10 13:45:01.479 | debug | (13990) Objects create System PubSub Client
amazon-dash.0 | 2021-02-10 13:45:01.476 | debug | (13990) Objects client ready ... initialize now
amazon-dash.0 | 2021-02-10 13:45:01.450 | debug | (13990) Redis Objects: Use Redis connection: 127.0.0.1:9001

**Comment by Apollon77** [comment]
Permission issue

"iobroker fix" is your friend

**Comment by daniel-lo** [comment]
@Apollon77

Which I already tried hundreds of times to no avail (btw. meant this with "iobroker fixing").

**Comment by Apollon77** [comment]
Really? Please post the output of "iobroker fix" command

**Comment by daniel-lo** [comment]
Maybe it has to do with this:

Error: The module '/opt/iobroker/node_modules/pcap/build/Release/pcap_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/pcap/pcap.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)


But all attempts to fix I made fail :-(

**Comment by daniel-lo** [comment]
iobroker fix:


==========================================================================
    Installing prerequisites (1/3)
==========================================================================

OK:1 http://archive.ubuntu.com/ubuntu bionic InRelease
OK:2 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease
Holen:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]
Holen:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74,6 kB]
Holen:5 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]
OK:6 https://deb.nodesource.com/node_10.x bionic InRelease
Holen:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1.883 kB]
Holen:8 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1.718 kB]
Holen:9 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [363 kB]
Holen:10 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1.543 kB]
Holen:11 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1.109 kB]
Holen:12 http://archive.ubuntu.com/ubuntu bionic-security/universe Translation-en [248 kB]
Es wurden 7.114 kB in 3 s geholt (2.696 kB/s).
Paketlisten werden gelesen... Fertig
Installed gcc-c++

==========================================================================
    Checking ioBroker user and directory permissions (2/3)
==========================================================================

Created /etc/sudoers.d/iobroker
Fixing directory permissions...

==========================================================================
    Checking autostart (3/3)
==========================================================================

Enabling autostart...
Autostart enabled!

==========================================================================

    Your installation was fixed successfully
    Run iobroker start to start ioBroker again!

==========================================================================

**Comment by Apollon77** [comment]
Yes also the compile erro migh be a reason.

do: 

cd /opt/iobroker/node_modules/pcap/
npm i

**Comment by daniel-lo** [comment]
Thanks .. did so and another fix afterwards.

node /opt/iobroker/node_modules/pcap/examples/network_grep.js
now gives me:
Listening on ens18

But the adapter still won't work:

amazon-dash.0 | 2021-02-11 17:57:41.977 | warn | (9088) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
amazon-dash.0 | 2021-02-11 17:57:41.977 | info | (9088) terminating
amazon-dash.0 | 2021-02-11 17:57:41.976 | info | (9088) cleaned everything up...
amazon-dash.0 | 2021-02-11 17:57:41.915 | error | (9088) socket: Operation not permitted
amazon-dash.0 | 2021-02-11 17:57:41.915 | error | at promiseReadSecret.then.then (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8479:34)
amazon-dash.0 | 2021-02-11 17:57:41.915 | error | at Adapter.emit (events.js:198:13)
amazon-dash.0 | 2021-02-11 17:57:41.915 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:53:9)
amazon-dash.0 | 2021-02-11 17:57:41.915 | error | at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:90:29)
amazon-dash.0 | 2021-02-11 17:57:41.915 | error | at Object.exports.createSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:131:12)
amazon-dash.0 | 2021-02-11 17:57:41.915 | error | at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:60:39)
amazon-dash.0 | 2021-02-11 17:57:41.915 | error | (9088) Error: socket: Operation not permitted
amazon-dash.0 | 2021-02-11 17:57:41.914 | error | (9088) unhandled promise rejection: socket: Operation not permitted
amazon-dash.0 | 2021-02-11 17:57:41.913 | error | (9088) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
amazon-dash.0 | 2021-02-11 17:57:41.910 | info | (9088) starting pcap session on default interface
amazon-dash.0 | 2021-02-11 17:57:41.890 | info | (9088) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v10.23.3, js-controller: 3.2.16
amazon-dash.0 | 2021-02-11 17:57:12.800 | warn | (8547) Terminated (UNCAUGHT_EXCEPTION): Without reason

**Comment by Apollon77** [comment]
then still permissions are not right.

please post output of

```
sudo getcap $(eval readlink -f `which node`)
```

**Comment by daniel-lo** [comment]
/home/daniel/.nvm/versions/node/v10.23.3/bin/node = cap_net_bind_service,cap_net_admin,cap_net_raw+eip

**Comment by daniel-lo** [comment]
sorry .. complete:

 /home/daniel/.nvm/versions/node/v10.23.3/bin/node = cap_net_bind_service,cap_net_admin,cap_net_raw+eip
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/daniel/='
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Apollon77** [comment]
You use nvm?? This is kind of unsupported because the installation fixer will NOT do all hist tasks correctly.
iobroker runs as user iobroker ... so you need to check the permissions for that user because with nvm (see also your nodejs path) your nodejsversion and so also permissions are user specific.

so you need to execute the crrect setcap commands for iobroker user ...

**Comment by daniel-lo** [comment]
I remember I did something that isn't favorable for iobroker .. but I am not a linux person knowing enough about how to roll this back or fix this. Is there maybe a tut you can point me to? (I don't even know why I use nvm .. probably some former tut I followed made me do this).

**Comment by Apollon77** [comment]
honestly ... I also have no idea . never used nvm. Maybe start a threadin iobroker forum to get support from some users on how to fix that

**Comment by daniel-lo** [comment]
I log on with my username with root rights and when I try to su to iobroker it asks me for a password which I don't know. How can I install setcap via iobroker user when I am logged in as daniel? Do you know?

**Comment by Apollon77** [comment]
should be

```
sudo setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw+eip' $(eval readlink -f `which node`)
```

**Comment by daniel-lo** [comment]
@Apollon77 

perfekt! green! thanks!
