### ISSUE TITLE
restart loop detected

### ISSUE THREAD

**Issue by daniel-lo** [PArns/ioBroker.amazon-dash#80]
Adapter is green but I get this warning

![grafik](https://user-images.githubusercontent.com/4311558/117532814-c3136100-afe9-11eb-8c28-15d780342e83.png)

**Comment by Apollon77** [comment]
Check the log please at the told timeoiint and check what was happening and post that log. Thiis message just tells you that there was something. Reasons need sto be check in Log. There was something at the gven timepoint!

**Comment by daniel-lo** [comment]
Good point .. it sais: 2021-02-24 07:18:20.862
How do I remove this error since happend long time ago.

**Comment by daniel-lo** [comment]
Message was outdated.
