### ISSUE TITLE
pcap is listed as optional dependency, but is required

### ISSUE THREAD

**Issue by ProfMertes** [PArns/ioBroker.amazon-dash#98]
Seit dem Update auf Node.js v16.20.2 + js.controller 5.0.12 verbindet sich der Adapter in der aktuellen Version nicht mehr und bleibt dauerhaft rot (Host nicht verbunden + Lebenszeichen Fehlanzeige).
Ich habe den Adapter immer sehr geschätzt, so wie die dazugehörige Entwicklungszeit die darin gesteckt wurde und würde mich sehr über ein Update freuen. Besten Dank schonmal!

**Comment by Apollon77** [comment]
Was steht denn do im Log? Mal "iob fix" ausgeführt?

Mit deinen bisherigen Info könnte nur meine Glaskugel helfen aber die muss ich erstmal entstauben.

**Comment by ProfMertes** [comment]
LOL! "iob fix" hatte ich schon erfolglos versucht.
Die Glaskugel kannst du im Schrank lassen. Vielleicht versuchen wir es doch erstmal mit dem log :-)
[amazon_dash_log.txt](https://github.com/PArns/ioBroker.amazon-dash/files/12590138/amazon_dash_log.txt)

**Comment by Apollon77** [comment]
Ok, did you also looked at the log you just sent me?
I repeat the first line:

> 	2023-09-12 21:08:47.413	info	Rebuild for adapter system.adapter.amazon-dash.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.


Tried that?

**Comment by ProfMertes** [comment]
Yes. I tried to execute this command in the amazon-dash directory but I was not able to find the corresponding adapter directory. For other adapters I could find the suitable directory.

**Comment by Apollon77** [comment]
should be /opt/iobroker/node_modules/iobroker.amazon-dash

**Comment by ProfMertes** [comment]
Thank you for the hint. I could execute the command inside the amazon-dash directory. 2 packages were added but /var/lib/dpkg/lock could not be opened although I am root (see console screenshot).
![2023-09-13_11h24_03](https://github.com/PArns/ioBroker.amazon-dash/assets/20865388/c4991e6f-715f-4237-bc8f-7bb0acd0791b)

**Comment by Apollon77** [comment]
Also mit der Fehlermeldungwürd eich mal mit "sudo" versuchen ... scheinbar will der linux pakete installieren.

**Comment by ProfMertes** [comment]
Sorry, hatte nicht erwähnt, dass ich das gleich danach mit sudo auch versucht habe, ebenfalls ohne Erfolg. 
Hatte den adapter auch schon komplett gelöscht und per Console im gestoppten Zustand erneut installiert.

**Comment by Apollon77** [comment]
Dann am besten adapter deinstallieren und neu installieren. Eine abhängies paket (pcap) ist nicht korrekt installiert

**Comment by ProfMertes** [comment]
Das hatte ich auch schon probiert (siehe oben). Habe die Prozedur dennoch erneut durchgeführt. Diesmal jedoch nochmal mit voragehender erneuter Installation von pcap per sudo und dann erst den Adapter. Ebenfalls ohne Erfolg.
![2023-09-13_12h19_12](https://github.com/PArns/ioBroker.amazon-dash/assets/20865388/9b3a1c0c-737f-4a3d-8b67-1e40fd362e76)

**Comment by Apollon77** [comment]
Nee ich rede von pcap npm paket nicht vom Binary Paket! Am besten mal den adapter vollständig deinstallieren (also nicht nur instanz, sondern auch Adapter)

**Comment by ProfMertes** [comment]
Pcap paket? Ich dachte das wäre genau das (wie in der readme beschrieben)? Wie lautet dann der Befehl?
Ich hatte immer Instanz + Adapter gelöscht und erneut installiert.

**Comment by Apollon77** [comment]
Ok ich verstehe lanbgsam. pcap ist im adater nur als optionale dependency gelistet, wird aber immer genutzt.

ok, dann mal etwas härter, wobei ich nicht verstehe was bei dir los ist
gehe in /opt/iobroker/node_modules/iobroker.amazon-dash, dann dort

npm install pcap

Was sagt das?

Dann bitte neu versuchen wenn das erfolgreich war.

So oder so ist dein OS outdated ... siehe die apt-get Fehler im letzten Screenshot!

**Comment by ProfMertes** [comment]
Bin leider erst dazu gekommen, aber dafür habe ich alles nochmal "from scratch" neu gemacht. Und siehe da, der amazon-dash adapter funktioniert nun endlich, wie er soll. Damit habe ich auch andere kleinere Baustellen behoben. Damit lagst du wohl richtig und es lag wohl daran, dass das OS outdated war. Hiermit schließe ich das issue und bedanke mich nochmal recht herzlich für den guten Support. Keep up the good work!
